export const siteContent = {
  site: {
    name: "Stephen Strout",
    title: "Film Editor / Producer",
    location: "Los Angeles, CA",
    email: "stephenstrout@me.com",
    website: "https://stephenstrout.com",
    imdb: "https://www.imdb.com/name/nm0835200/?ref_=nv_sr_srsg_0_tt_0_nm_4_in_0_q_stephen%20B%20Strout",
  },
  profile: {
    kicker: "Profile",
    title: "Editing For The New Millenium",
    intro:
      "Stephen Strout is a documentary editor, producer, and director based in Los Angeles.",
    paragraphs: [
      "Stephen is best known for editing documentaries and feature films. He made his directorial debut with the award-winning feature documentary <em>Revolution Green</em>. He won a Peabody Award for documentary editing for <em>Black Sky: The Race For Space</em> and a Telly Award for the feature trailer <em>Lone Survivor</em>. Throughout his career, his editing has been critically acclaimed, earning multiple Emmy nominations and one win through collaborations with Peter Berg, Rory Kennedy, Mark Bailey, Zackary Drucker, Maria Taylor, Christopher Cowen, Emmett and Brendan Malloy, and Academy Award winners Eric Simonson and Richard Trank.",
    ],
    recognition:
      "Peabody Award-2005, Black Sky: The Race For Space\nGolden Cine Eagle-2005, Black Sky: The Race For Space\nTelly Award-2013, Lone Survivor Trailer\nEmmy winner-2016, State Of Play-Fighting Chance\nEmmy Nomination-2026, Enigma\nCinema Eye Nomination-2026, Enigma\nGLAAD Outstanding Documentary Nomination-2026",
  },
  projectsIntro:
    "A selected list of films and series, with a behind the scenes story about the inception of each project.",
  contact: {
    heading: "CONTACT",
    body: "For editorial collaborations, producing work, or availability inquiries, email is the best way to reach Stephen directly.",
  },
  projects: [
    {
      slug: "field-generals-history-of-the-black-quarterback",
      layout: "tall",
      title: "Field Generals: History Of The Black Quarterback",
      year: "2026",
      type: "Documentary series",
      role: "Editor",
      description:
        "As recently as 1968, it was widely believed in the NFL that players like Marlin Briscoe, Joe Gilliam and James Harris lacked the character to play QB. Star college QBs like Tony Dungy are switched to lesser positions by their pro teams; others, like future Hall of Famer Warren Moon, take alternative routes. While Ronald Reagan campaigns and governs on a wave of white backlash against Black progress, Doug Williams endures racial bias and personal tragedy to become the first Black QB to win a Super Bowl. Eventually Randall Cunningham, Donovan McNabb and Michael Vick revolutionized how the position would be played forever.",
      studio: "Broadway Video / Magic Lemonade / NFL Films / NBC Sports",
      imageBaseName: "Field_Generals2",
      posterAlt: "One-sheet artwork for Field Generals: History Of The Black Quarterback",
      links: [
        {
          label: "Project Page",
          href: "https://www.peacocktv.com/blog/watch-peacocks-field-generals-history-of-the-black-quarterback",
        },
        {
          label: "Watch Trailer",
          href: "https://www.youtube.com/watch?v=lUJlbb5lVA8",
        },
      ],
    },
    {
      slug: "enigma",
      layout: "wide",
      title: "Enigma",
      year: "2025",
      type: "Documentary film",
      role: "Producer",
      description:
        "Acclaimed filmmaker Zackary Drucker explores questions of identity and survival, revealing the disparate but intertwined stories of iconic pioneers April Ashley and Amanda Lear. Their experiences, varied and complex, highlight the costs associated with living their truths and explore what is gained and lost by defining their identities. The film had its world premiere at the 2025 Sundance Film Festival.",
      studio: "Pacific Films / Story Syndicate / 5 All In The Fifth / HBO",
      imageBaseName: "Enigma2",
      posterAlt: "One-sheet artwork for Enigma",
      links: [
        {
          label: "Project Page",
          href: "https://www.hbomax.com/movies/enigma/b4ce423a-0c50-4a36-9e7d-3a9bc30530cf",
        },
        {
          label: "Watch Trailer",
          href: "https://www.youtube.com/watch?v=QyV0pqwjJXk",
        },
      ],
    },
    {
      slug: "the-synanon-fix-did-the-cure-become-a-cult",
      layout: "wide",
      title: "The Synanon Fix: Did The Cure Become A Cult",
      year: "2024",
      type: "Documentary series",
      role: "Co-editor",
      description:
        "The Synanon Fix is an American documentary series directed and produced by Rory Kennedy. It explores the rise and fall of Synanon, told through the eyes of former members, into its descent into a cult. The Synanon Fix had its world premiere at the 2024 Sundance Film Festival.",
      studio: "Moxie Films / HBO",
      imageBaseName: "The_Synanon_Fix",
      posterAlt: "One-sheet artwork for The Synanon Fix",
      links: [
        {
          label: "Watch Trailer",
          href: "https://www.youtube.com/watch?v=Y8Z8xMmly1M",
        },
      ],
    },
    {
      slug: "saudi-pro-league-kickoff",
      layout: "tall",
      title: "Saudi Pro League: Kickoff",
      year: "2024",
      type: "Documentary series",
      role: "Editor",
      description:
        "Dive deep into the high-stakes world of Saudi football, with an insider's view into 5 clubs competing for the title of Saudi Pro League champion, Al Nassr, Al Hilal, Al Ittihad, Al Ahli, and Al Etiffaq. With the arrival of Ronaldo to the Saudi Pro League, fans witness Ronaldo's impact on Al Nassr, as he drives the team with his relentless pursuit of victory, Benzema's journey as he grapples with the weight of expectations at Al Ittihad, the tension at Al Hilal surrounding Neymar's injury, and the rising local talent like Salem Al Dawsari (Al Hilal), Feras Al Buraikan (Al Ahli), Talal Haji (Al Ittihad), and Abdulrahman Ghareeb (Al Nassr), showcasing the depth and passion of Saudi football's next generation.",
      studio: "Whisper / Netflix",
      imageBaseName: "Saudi_Pro_League_Kickoff",
      posterAlt: "One-sheet artwork for Saudi Pro League: Kickoff",
      links: [
        {
          label: "Project Page",
          href: "https://www.netflix.com/title/81783473",
        },
        {
          label: "Watch Trailer",
          href: "https://www.youtube.com/watch?v=2ivIYBD4tfQ",
        },
      ],
    },
    {
      slug: "chasing-waves",
      layout: "wide",
      title: "Chasing Waves",
      year: "2023",
      imageBaseName: "Chasing_Waves",
      posterAlt: "One-sheet artwork for Chasing Waves",
      links: [],
    },
    {
      slug: "revolution-green",
      layout: "tall",
      title: "Revolution Green",
      year: "Year to add",
      imageBaseName: "Revolution_Green",
      posterAlt: "One-sheet artwork for Revolution Green",
      links: [],
    },
    {
      slug: "above-and-beyond",
      layout: "tall",
      title: "Above And Beyond",
      year: "Year to add",
      imageBaseName: "Above_And_Beyond",
      posterAlt: "One-sheet artwork for Above And Beyond",
      links: [],
    },
    {
      slug: "the-new-normal",
      layout: "wide",
      title: "The New Normal",
      year: "Year to add",
      imageBaseName: "The_New_Normal",
      posterAlt: "One-sheet artwork for The New Normal",
      links: [],
    },
    {
      slug: "the-real-robin-hood",
      layout: "wide",
      title: "The Real Robin Hood",
      year: "Year to add",
      imageBaseName: "The_Real_Robin_Hood",
      posterAlt: "One-sheet artwork for The Real Robin Hood",
      links: [],
    },
    {
      slug: "delta-divers",
      layout: "wide",
      title: "Delta Divers",
      year: "Year to add",
      imageBaseName: "Delta_Divers",
      posterAlt: "One-sheet artwork for Delta Divers",
      links: [],
    },
    {
      slug: "maldita",
      layout: "tall",
      title: "Maldita",
      year: "Year to add",
      imageBaseName: "Maldita",
      posterAlt: "One-sheet artwork for Maldita",
      links: [],
    },
    {
      slug: "will-of-the-warrior",
      layout: "tall",
      title: "Will Of The Warrior",
      year: "Year to add",
      imageBaseName: "Will_Of_The_Warrior",
      posterAlt: "One-sheet artwork for Will Of The Warrior",
      links: [],
    },
    {
      slug: "state-of-play-fighting-chance-3",
      layout: "wide",
      title: "State Of Play: Fighting Chance 3",
      year: "State Of Play",
      imageBaseName: "State_Of_Play_Fighting_Chance3",
      posterAlt: "One-sheet artwork for State Of Play: Fighting Chance 3",
      links: [],
    },
    {
      slug: "state-of-play-fighting-chance-2",
      layout: "wide",
      title: "State Of Play: Fighting Chance 2",
      year: "State Of Play",
      imageBaseName: "State_Of_Play_Fighting_Chance2",
      posterAlt: "One-sheet artwork for State Of Play: Fighting Chance 2",
      links: [],
    },
    {
      slug: "state-of-play-fighting-chance",
      layout: "wide",
      title: "State Of Play: Fighting Chance",
      year: "State Of Play",
      imageBaseName: "State_Of_Play_Fighting_Chance",
      posterAlt: "One-sheet artwork for State Of Play: Fighting Chance",
      links: [],
    },
    {
      slug: "state-of-play-culture-shock",
      layout: "wide",
      title: "State Of Play: Culture Shock",
      year: "State Of Play",
      imageBaseName: "State_Of_Play_Culture_Shock",
      posterAlt: "One-sheet artwork for State Of Play: Culture Shock",
      links: [],
    },
    {
      slug: "state-of-play-broken",
      layout: "wide",
      title: "State Of Play: Broken",
      year: "State Of Play",
      imageBaseName: "State_Of_Play_Broken",
      posterAlt: "One-sheet artwork for State Of Play: Broken",
      links: [],
    },
    {
      slug: "state-of-play-first-wives",
      layout: "wide",
      title: "State Of Play: First Wives",
      year: "State Of Play",
      imageBaseName: "State Of Play_First Wives",
      posterAlt: "One-sheet artwork for State Of Play: First Wives",
      links: [],
    },
    {
      slug: "state-of-play-trophy-kids",
      layout: "wide",
      title: "State Of Play: Trophy Kids",
      year: "2013",
      imageBaseName: "State_Of_Play_Trophy Kids",
      posterAlt: "One-sheet artwork for State Of Play: Trophy Kids",
      links: [],
    },
    {
      slug: "on-freddie-roach",
      layout: "wide",
      title: "On Freddie Roach",
      year: "2012",
      imageBaseName: "On_Freddie_Roach",
      posterAlt: "One-sheet artwork for On Freddie Roach",
      links: [],
    },
    {
      slug: "against-the-tide",
      layout: "wide",
      title: "Against The Tide",
      year: "Year to add",
      imageBaseName: "Against_The_Tide",
      posterAlt: "One-sheet artwork for Against The Tide",
      links: [],
    },
    {
      slug: "karaoke-superstars",
      layout: "wide",
      title: "Karaoke Superstars",
      year: "Year to add",
      imageBaseName: "Karaoke_Superstars",
      posterAlt: "One-sheet artwork for Karaoke Superstars",
      links: [],
    },
    {
      slug: "black-sky-the-race-for-space",
      layout: "wide",
      title: "Black Sky: The Race For Space",
      year: "Year to add",
      imageBaseName: "Black_Sky_The_Race-For_Space",
      posterAlt: "One-sheet artwork for Black Sky: The Race For Space",
      links: [],
    },
    {
      slug: "epic-bill",
      layout: "wide",
      title: "Epic Bill",
      year: "Year to add",
      imageBaseName: "Epic_Bill",
      posterAlt: "One-sheet artwork for Epic Bill",
      links: [],
    },

    {
      slug: "into-pitch-black",
      layout: "tall",
      title: "Into Pitch Black",
      year: "Year to add",
      imageBaseName: "Into_Pitch_Black",
      posterAlt: "One-sheet artwork for Into Pitch Black",
      links: [],
    },
  ],
};
